### ISSUE TITLE
Daily limit

### ISSUE THREAD

**Issue by Bara** [Munzy/blackbox#1]
Is there any limitation for your site ( https://blackbox.ipinfo.app/ ) ?

**Comment by Munzy** [comment]
There are no limitations on how many queries you can send against the site. Just keep it reasonable. 

Is there a specific limit you are worried about hitting?

**Comment by Bara** [comment]
👍 No that's fine, I'll work with caching to reduce the hits/calls. I know a few sites that's limited daily queries to 1k (maybe more or less), that's why I asked.

**Comment by Munzy** [comment]
No limits, don't plan on adding any for this section of the API. 

I'd say don't bother with caching unless it benefits you personally with your application. We are running Cloudflare as a cache to help with frequent repeat queries. It also allows us to purge the cache when we feel a large modification to already cached data is needed.

**Comment by Bara** [comment]
I just realized that you're "MUN" on AlliedMods and you already replied my question ( https://forums.alliedmods.net/showpost.php?p=2672593&postcount=51 ). 🤦‍♂ 

I'll close this issue and thanks for you time.
