### ISSUE TITLE
Bunch of known VPN addresses not being blocked:

### ISSUE THREAD

**Issue by g1xn** [Munzy/blackbox#2]
Hey, I found a bunch of IP addresses that are used by "NordVPN" and most if not all of them are not blocked by the API.

The IP that got through was "165.231.210.180" and I found a GitHub list containing all of the addresses, see below:

https://gist.github.com/JamoCA/eedaf4f7cce1cb0aeb5c1039af35f0b7

Also, thank you for providing such a great service and replacement for the other detection services that are now discontinued, if there's anything I can do to help I'm more than happy to assist you

**Comment by Munzy** [comment]
I was looking at the updated list featured on that link. It didn't provide that IP address you mentioned. I am not sure which IP list is the most updated, so I used two of them currently. 

I think we still need to analyze a better way of getting updated IP addresses from them.

**Comment by g1xn** [comment]
Hmm, well adding the Nord-lists helped improve detection substantially.

I'm not entirely sure if there's an easy way to pull IP ranges from VPN providers so I found a massive list of datacentre IP's which is maintained by periodically, also includes IPv4 & IPv6 with IP ranges:

https://github.com/ejrv/VPNs

I haven't had time to look through the source code and check the blocklists & detection methods you're using currently but I figured this list would be extremely helpful in detecting Tor exit nodes which are updated hourly:

https://github.com/SecOps-Institute/Tor-IP-Addresses

**Comment by Munzy** [comment]
Good Morning!

I am taking a look at the VPN list you provided, and thinking of the best way to handle it. I am thinking of maybe looking through it and determining the ASN for each IP. It might be the easiest method.

Now on to your TOR list. We currently already have one tor list we search through for exit nodes. I felt like the list you provided would be beneficial. As such, I have added it to the appliance and will combine the two lists.
