### ISSUE TITLE
Add IP to blacklist.

### ISSUE THREAD

**Issue by oaus** [Munzy/blackbox#714]
__Q: What should it be marked as?__

VPN/Proxy

Q:  What is the IP Address?

68.2.52.76

__Q: What is the internet provider?__

Cox Communications

https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/68.2.52.76

**Comment by Munzy** [comment]
I can't seem to find anything indicating this is being used as a proxy beyond that free check. What gives you the impression that this IP is being used as a proxy server?
