### ISSUE TITLE
An IP is being marked incorrectly

### ISSUE THREAD

**Issue by doskipaul** [Munzy/blackbox#718]
__Q: What are you currently seeing?__

this IP used fake user-agent to get into my site and statred submiting random informations on my site's contact form

__Q: What should it be marked as?__

This ip should be marked as a hosting IP

Q:  What is the IP Address?

207.32.56.173
64.26.151.55

__Q: What is the internet provider?__

Aureon Network Services
Rogers Cable

**Comment by Munzy** [comment]
Hmm, I think we can do Aureon Network Services because that is a hosting provider. Rogers Cable is residential though. I am not comfortable adding it to our hosting list. 

Let me get to work on it and see if I can find an alternative.

**Comment by doskipaul** [comment]
Yeah Aureon Network Services is a hosting provider , But I think Rogers Cable reserved some of it IP ranges for bots and crawlers.
You should add crawler detector using user-agent too sir ! Thanks for the hard work you do
