### ISSUE TITLE
Cloudflare's DNS 1.1.1.1

### ISSUE THREAD

**Issue by bobbonomo** [Munzy/blackbox#720]
Cloudflare's 1.1.1.1 should be treated like 8.8.8.8.8
Same goes for IBM's quad 9 9.9.9.9
Open DNS is  208.67.222.222 and 208.67.220.220
All except 8.8.8.8 return Y

OR
maybe let 8.8.8.8 return Y

**Comment by Munzy** [comment]
We would likely want this to report Y. 

Google's ASN is complex, which makes it hard to dynamically filter everything. I'll see if possibly we can add a manual IP listing.

**Comment by Munzy** [comment]
We have deployed a patch for the above. 

Changes will take full effect as cache slowly wears off.
