### ISSUE TITLE
IP Data Issues

### ISSUE THREAD

**Issue by stefanx111** [Munzy/blackbox#721]
__Q: What are you currently seeing?__

N

__Q: What should it be marked as?__

Y

Q:  What is the IP Address?

1. 5.8.16.166
2. 195.88.86.12

__Q: What is the internet provider?__

1. AS44050 Petersburg Internet Network ltd
2. AS16315 Lucid Networks (contracts) Ltd

**Comment by Munzy** [comment]
Thank you for the report. I'll get on these additions merged in shortly.
