### ISSUE TITLE
IP to Proxy / VPN list

### ISSUE THREAD

**Issue by ShadowsAdi** [Munzy/blackbox#722]
__Q: What are you currently seeing?__

N

__Q: What should it be marked as?__

Y

Q:  What is the IP Address?

114.171.194.212

__Q: What is the internet provider?__

AS4713 NTT Communications Corporation

__Q: What other info can you provide us?__

ASN: AS4713
https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/114.171.194.212

**Comment by Munzy** [comment]
Can you provide me more details on what you are seeing from this IP address?

**Comment by ShadowsAdi** [comment]
This IP address is provided as VPN Tunnel on ProtonVPN Desktop App.

**Comment by Munzy** [comment]
I am still looking for a list of ProtonVPN IPs. If you can find such a think please let me know.

I've manually added the IPs you mentioned.
