### ISSUE TITLE
IP to Proxy / VPN list

### ISSUE THREAD

**Issue by ShadowsAdi** [Munzy/blackbox#723]
__Q: What are you currently seeing?__

N

__Q: What should it be marked as?__

Y

Q:  What is the IP Address?

90.149.44.63 

__Q: What is the internet provider?__

AS2527 So-net Entertainment Corporation

__Q: What other info can you provide us?__

https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/90.149.44.63

**Comment by Munzy** [comment]
This looks like Sony Network. 

Do they run VPNs out of this? I am hesitant to ban corporate ASNs.

**Comment by ShadowsAdi** [comment]
Yes, they run VPNs services on that IP, exactly, ProtonVPN provides this.

**Comment by Munzy** [comment]
Thank you, let me see if I can find a listing of protonvpn servers.

**Comment by Munzy** [comment]
I am still looking for a list of ProtonVPN IPs. If you can find such a think please let me know.

I've manually added the IPs you mentioned.
