### ISSUE TITLE
212.103.50.74 kaspersky  vpn ip

### ISSUE THREAD

**Issue by mhndm** [Munzy/blackbox#725]
__Q: What are you currently seeing?__

The site is marking ip as normal ip

__Q: What should it be marked as?__

its must be a vpn ip

Q:  What is the IP Address?

212.103.50.74

__Q: What is the internet provider?__

kaspersky vpn service

**Comment by Munzy** [comment]
Site looks to be working correctly and marking the site with "Y" for being proxy. 

![image](https://user-images.githubusercontent.com/4347462/131528605-a9c32087-0756-4222-9f6e-9cc0ee1bcb6c.png)
