### ISSUE TITLE
New Proxy IPs

### ISSUE THREAD

**Issue by ShadowsAdi** [Munzy/blackbox#729]
__Q: What are you currently seeing?__
N

__Q: What should it be marked as?__
Y

Q:  What is the IP Address?
92.53.59.119
195.47.194.46
85.10.50.176
89.164.99.107
176.222.34.111

__Q: What is the internet provider?__
BLIZOO
A.b Internet Solutions
A1 Hrvatska
Iskon Internet
Optima Telekom

__Q: What other info can you provide us?__
AS43612
AS35758
AS29485
AS13046
AS34594

![image](https://user-images.githubusercontent.com/54354938/135127479-dbd72078-980b-4e82-b129-b4a7de5506fc.png)
![image](https://user-images.githubusercontent.com/54354938/135146554-7bdd51ca-01d1-4ea8-9c72-2e7b422f88d7.png)
![image](https://user-images.githubusercontent.com/54354938/135145967-a921e558-46b3-45b4-baa7-4f253628e16c.png)
![image](https://user-images.githubusercontent.com/54354938/135146333-a818ca79-e061-496c-8d20-c69d896c464f.png)
![image](https://user-images.githubusercontent.com/54354938/135146474-ba9e6dd3-eb48-4166-a9d7-ae1999f73389.png)

**Comment by ShadowsAdi** [comment]
New IP: 
159.48.53.142

AS62240

![image](https://user-images.githubusercontent.com/54354938/135149912-9d073f62-1198-41c1-bdcb-9e317e37c2c6.png)

**Comment by Munzy** [comment]
I'll take a look at these shortly.

It's hard finding a nice thick listing of NordVPN these days, and they seem to recently added some more. 

The last one you entered needs to be added via an AS block as they are a hosting provider.

**Comment by ShadowsAdi** [comment]
185.65.50.65
![image](https://user-images.githubusercontent.com/54354938/135309830-6c9f403f-634d-49d1-8742-1ceb393e185a.png)
