### ISSUE TITLE
problem getting json data

### ISSUE THREAD

**Issue by droflim** [Munzy/blackbox#731]
Hello, nice to greet you, first of all congratulate you for this excellent api, it has been very useful to me to block proxies and vpn in my network that has .unrealircd, my only problem is with this provider servihosting networks sl, which detects some false positives reported by users, that is why I would like to have access to json to disregard hosting as such

**Comment by Munzy** [comment]
The JSON API should be available here: 

https://rapidapi.com/CMunroe/api/blackbox/
