### ISSUE TITLE
It detects this ip as vpn. It's not vpn, please unlock ip

### ISSUE THREAD

**Issue by Trivort** [Munzy/blackbox#732]
It detects this ip as vpn. It's not vpn, please unlock ip 212.79.96.253

**Comment by Munzy** [comment]
@Trivort 

What is the IP used for? Is it used at a hosting provider or otherwise?

**Comment by Trivort** [comment]
This is the player IP of one of my servers. hosting provider i think

**Comment by Munzy** [comment]
Is the player tunneling the traffic to a server, then to yours?

**Comment by Trivort** [comment]
think so. It pops up in the game console
Server IP address 192.168.31.122:27015 Connecting to 145.239.236.14:27160 ...

Call accepted until 145.239.236.14:27160 *

His IP: 212.79.96.253
His old IP: 212.79.96.12
On the old ip address, everything seemed to work for him, after replacing the router, the server throws it out with the reason VPN / proxy block, based on blackbox

**Comment by Munzy** [comment]
http://www.freetel.cz/

This is the providers website for that IP address.

It is a datacenter, so I don't think we should remove the block on our side. Instead, I would add a whitelist for that IP if they are a valid player to you. From what I can tell, they are likely using this to proxy their connection.
