### ISSUE TITLE
Question regarding the API response types

### ISSUE THREAD

**Issue by pywc** [Munzy/blackbox#733]
Hello!

I wanted to mention that I'm loving this proxy detection API!

While I was using the API, I figured out that it returns 'Y' for ones they are VPN/Proxies and 'N' otherwise.
However, I went into a response from an IP that says 'E' today, any explanations on what that could mean?

Thanks!

**Comment by Munzy** [comment]
E = Error. 

It could be that the IP address submitted was invalid, or a backend query failed. If it is happening on a specific address let me know, and I can investigate if something is amiss.

**Comment by pywc** [comment]
The specific IP that returns 'E' is here:
https://defuse.ca/b/DzopjvwHJWukm6U08Gz7JX

(I pasted the IP into a secure pastebin due to privacy issues)

**Comment by Munzy** [comment]
Can you tell me if you re-query the IP does it still return "E"?

I just tested here at home and I am seeing it come out as "N". It is possible that cloudflare might have cached a bad record.

**Comment by pywc** [comment]
Yes, I'm still seeing an 'E' on my end.
I'm testing with this URL: https://blackbox.ipinfo.app/lookup/

**Comment by Munzy** [comment]
Give it a shot now, I cleared out cache on it.

**Comment by pywc** [comment]
That worked! Thanks 👍
