### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by Sn00zr** [Munzy/blackbox#736]
__Q: What are you currently seeing?__

37.202.60.196
174.140.181.223
76.74.71.51

__Q: What should it be marked as?__

NOT VPN

Q:  What is the IP Address?

37.202.60.196
174.140.181.223
76.74.71.51

__Q: What is the internet provider?__

<multiple>

__Q: What other info can you provide us?__

Can you please assist in marking these IPs as not VPN? Thank you!

**Comment by Munzy** [comment]
37.202.60.196:
* This looks to be hosting. https://www.blix.com/
* Can you confirm?

174.140.181.223:
* looks to be a mixed of hosting https://kwic.com/business/
* Need to figure out what list is suggesting this for blocking.

76.74.71.51:
* GTT Backbone. So marked as hosting.

Are you utilizing these IPs at all? What are you using them for?

**Comment by Munzy** [comment]
Most of these came from when I initially was starting the project. Many of these were reported as "hosting" providers at the time. 

We do some mapping of hosting providers via ASN. Since it is highly unlikely someone is playing a video game from a known VPS provider. 

76.74.71.51:
Can you confirm this is there actual IP address? This one is the only one that seems odd at the moment, as the more I dig into it the more it seems like this shouldn't and wouldn't be used by a residential IP.

**Comment by Munzy** [comment]
All the IPs have been updated minus the 76.74.71.51. Still want to look further into that one, as unblocking GTT seems like I am letting a lot more through than I would like.

**Comment by Munzy** [comment]
https://rapidapi.com/CMunroe/api/blackbox/

We use a lot of caching to keep request volumes in control. I double checked, and the current un-cached version is accurate.

**Comment by Munzy** [comment]
Sadly, looking this over. I don't think I have any good options here. The IP is smack dab center in a huge Tier 1 network provider that mostly does IP backhaul for large hosting providers and the likes. 

I think I will need to see if I can find a way to automate the finding of Cox's ips if this is the case. It just seems silly the way they have it setup. 

For the time being I would suggest looking to see if you can "whitelist" that particular IP for that player.

**Comment by CameronMunroe** [comment]
Here is an idea, tell me what you think.

We create a small docker pod. It would need to run on port 80. Using the host file of your Linux or Windows host machine you point blackbox.ipinfo.app to the host running the docker pod. The docker image would have a whitelist and blacklist file where you could have a list of IPs that are added at your digression. If the IP is not found in either the whitelist or blacklist files, it would reach out to the actual blackbox.ipinfo.app site and pull down the appropriate record. 

This would then allow plugins that don't support a whitelist to have a whitelist. The only downside is you would need to run an entire docker pod just for this purpose. 

Tell me if you are interested and I can try and create it.

**Comment by Munzy** [comment]
Not seen any response to this, so going to close ticket. Feel free to reopen.
