### ISSUE TITLE
False-Positive Detection

### ISSUE THREAD

**Issue by revCat** [Munzy/blackbox#739]
__Q: What are you currently seeing?__
Y

__Q: What should it be marked as?__
N

Q:  What is the IP Address?
211.231.74.229
183.109.28.141
211.48.89.159
221.163.29.84
220.127.218.203
14.49.211.177
211.228.193.195
121.171.210.170
203.234.130.224
221.163.29.84
218.157.13.160
etc..

__Q: What is the internet provider?__
Korea Telecom

__Q: What other info can you provide us?__
[AS4766] (https://ipinfo.io/AS4766)

Korea Telecom (KT) is a South Korean telecommunications company.
The IPs listed are pure home IPs, not VPN or proxy connections or IDC.

Please check. Thank you!

**Comment by Munzy** [comment]
Howdy, 

I see the issue you are facing and I am investigating. This looks to be coming from a third-party list, and I am trying to confirm why KT is added.

**Comment by flysk1** [comment]
I hope this project continue public and fully free for everyone, and keep contribute for it!

**Comment by CameronMunroe** [comment]
This should be resolved.

The cache might take a bit to clear out, but KT has been removed from new announcements.
